version: "3.8"

services:
  server:
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: ${SERVER_COMMAND:-uvicorn main:app --host 0.0.0.0 --port 8000 --reload}

  mongo:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
