version: "3"

services:
  web:
    build:
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ../.env.development
    ports:
      - 8000:8000
    volumes:
      - ../:/app
    command: sh -c "ls -la /app && ls -la /app/tests/ && pytest -v -s"
